import {analyseTeam,percentage,teamKey,validateConfig} from './analysis-engine.js';
const root=document.getElementById('analysis-panel');
const storageKey='volleyball-analysis:setters:v1';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=1)=>n===null||n===undefined?'—':Number(n).toFixed(d);
const pct=n=>n===null||n===undefined?'—':`${fmt(n)}%`;
const safeUrl=url=>{try{const u=new URL(url);return u.protocol==='https:'?u.href:'#';}catch{return '#';}};
let context=null,index=null,published={version:1,teams:{}},local={version:1,teams:{}},loadError='',team='',selectedMatch='all',selectedSet='',setupMatch='',setupSet='',request=0,loaded=[],minTurns=0,sort='servingTurns',report=null;
try{const saved=localStorage.getItem(storageKey);if(saved)local=validateConfig(JSON.parse(saved));}catch{loadError='Saved setter choices could not be read. Import your exported configuration to restore them.';}
const params=new URLSearchParams(location.search);
let firstContext=true;
function merged(){const c=structuredClone(published);for(const [key,t]of Object.entries(local.teams)){c.teams[key]??={matches:{}};Object.assign(c.teams[key].matches,t.matches);}return c;}
async function json(url){const r=await fetch(url);if(!r.ok)throw new Error(`Could not load ${url} (HTTP ${r.status}).`);return r.json();}
function download(name,content,type='application/json'){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function csv(rows,columns){const cell=value=>{let s=String(value??'');if(typeof value==='string'&&/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};return '\uFEFF'+[columns.map(c=>cell(c[1])).join(','),...rows.map(r=>columns.map(c=>cell(r[c[0]])).join(','))].join('\r\n');}
const serveColumns=[['name','Player'],['servingTurns','Serving turns'],['firstRalliesWon','First rallies won'],['firstRallyWinPct','First-rally win %','pct'],['zeroPointTurns','Zero-point turns'],['onePointTurns','1 point'],['twoPointTurns','2 points'],['threeToFourPointTurns','3–4 points'],['fivePlusPointTurns','5+ points'],['threePlusRunPct','3+ run %','pct'],['bestPointRun','Best point run'],['sets','Sets played'],['matches','Matches played'],['serves','Serves'],['serveWinPct','Serve win %','pct'],['servesPerSet','Serves / set','dec'],['pointsPerTurn','Points / turn','dec']];
const rotationColumns=[['rotation','Rotation'],['rallies','Rallies'],['pointsWon','Points won'],['pointsLost','Points lost'],['netPointsPer100','Net points / 100','signed'],['serves','Serves'],['serveWins','Serve wins'],['serveWinPct','Serve win %','pct'],['received','Received'],['sideOuts','Side-outs'],['sideOutPct','Side-out %','pct']];
function table(rows,columns,label){return `<div class="a-table-wrap" tabindex="0" role="region" aria-label="${esc(label)}; scroll horizontally for all columns"><table class="a-table"><thead><tr>${columns.map(c=>`<th scope="col">${esc(c[1])}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr class="${r.rotation==='Unconfirmed'?'a-unconfirmed':''}">${columns.map(([key,,type],i)=>{const v=r[key];const text=type==='pct'?pct(v):type==='dec'?fmt(v,2):type==='signed'?(v===null?'—':`${v>0?'+':''}${fmt(v)}`):esc(v);return `<${i?'td':'th'} ${i?'':'scope="row"'} class="${type==='signed'&&v!==null?(v<0?'a-negative':'a-positive'):''}">${text}${key==='name'&&r.servingTurns<10?'<span class="a-chip">small sample</span>':''}</${i?'td':'th'}>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;}
function entries(){return (index?.matches||[]).filter(m=>+m.leagueId===+context?.leagueId&&[m.home,m.away].includes(team));}
function matchLabel(m){return `${m.date} · ${m.home} vs ${m.away} · ${m.score}`;}
function getSelection(matchId,setNumber=''){const m=merged().teams[teamKey(context.leagueId,team)]?.matches?.[matchId]||{};return setNumber?(m.sets?.[setNumber]||m):m;}
function saveLocal(){localStorage.setItem(storageKey,JSON.stringify(local));}
function roleOptions(value){return [['','—'],['setter','Setter'],['backup','Backup']].map(([v,t])=>`<option value="${v}" ${v===value?'selected':''}>${t}</option>`).join('');}
function renderSetup(){const target=root.querySelector('#a-setup-content');if(!target)return;const ready=loaded;if(!ready.length){target.innerHTML='<p class="a-note">Setter selection becomes available when a match PDF has been read.</p>';return;}
if(!ready.some(m=>m.id===setupMatch))setupMatch=(ready.find(m=>m.id===selectedMatch)||ready[0]).id;
const match=ready.find(m=>m.id===setupMatch),side=match.home===team?'home':'away',selection=getSelection(setupMatch,setupSet), hasOverride=!!merged().teams[teamKey(context.leagueId,team)]?.matches?.[setupMatch]?.sets?.[setupSet];
target.innerHTML=`<div class="a-filter"><label>Match to configure<select id="a-setup-match">${ready.map(m=>`<option value="${esc(m.id)}" ${m.id===setupMatch?'selected':''}>${esc(matchLabel(m))}</option>`).join('')}</select></label><label>Apply to<select id="a-setup-set"><option value="">Whole match</option>${match.sets.map(s=>`<option value="${s.number}" ${String(s.number)===setupSet?'selected':''}>Set ${s.number} override</option>`).join('')}</select></label></div>
<div class="a-filter"><label>When two selected setters are on court<select id="a-system"><option value="single" ${selection.system==='single'||!selection.system?'selected':''}>Leave ambiguous rotations Unconfirmed</option><option value="back-row" ${selection.system==='back-row'?'selected':''}>Use the back-row setter (6–2)</option><option value="front-row" ${selection.system==='front-row'?'selected':''}>Use the front-row setter (4–2)</option></select></label></div>
<p class="a-note">Choose your setters for this match. A backup is used only when no selected setter is in the rotation lineup. ${setupSet&&!hasOverride?'This set currently inherits the whole-match choices. Saving here creates an override.':''}</p>
<div class="a-setters">${match.rosters[side].filter(p=>!p.libero).map(p=>`<label class="a-player-role"><span><b>#${esc(p.number)}</b>${esc(p.name)}</span><select data-shirt="${esc(p.number)}" aria-label="Role for ${esc(p.name)}">${roleOptions(selection.setters?.includes(p.number)?'setter':selection.fallbacks?.includes(p.number)?'backup':'')}</select></label>`).join('')}</div>
<div class="a-actions"><button id="a-save" class="a-primary">Save setters</button>${setupSet?'<button id="a-inherit">Use whole-match choices</button>':'<button id="a-clear">Clear this match’s setters</button>'}<span class="a-save-message" id="a-save-message" role="status"></span></div>
<p class="a-note">Saved on this browser. Export setter choices below to share them with teammates. Libero exchanges are absent from the PDF; choose setters who stay in the regular rotation lineup.</p>`;
target.querySelector('#a-setup-match').onchange=e=>{setupMatch=e.target.value;setupSet='';renderSetup();};target.querySelector('#a-setup-set').onchange=e=>{setupSet=e.target.value;renderSetup();};
const write=(clear=false,inherit=false)=>{const key=teamKey(context.leagueId,team);local.teams[key]??={matches:{}};const previous=structuredClone(merged().teams[key]?.matches?.[setupMatch]||{setters:[],fallbacks:[],system:'single'});const next={setters:[],fallbacks:[],system:target.querySelector('#a-system').value};if(!clear)target.querySelectorAll('[data-shirt]').forEach(s=>{if(s.value)next[s.value==='setter'?'setters':'fallbacks'].push(s.dataset.shirt);});
if(setupSet){previous.sets??={};if(inherit)delete previous.sets[setupSet];else previous.sets[setupSet]=next;local.teams[key].matches[setupMatch]=previous;}else local.teams[key].matches[setupMatch]=clear?{setters:[],fallbacks:[],system:'single'}:{...next,...(previous.sets?{sets:previous.sets}:{})};
try{saveLocal();renderSetup();root.querySelector('#a-save-message').textContent='Saved. Tables updated.';renderReport();}catch{root.querySelector('#a-save-message').textContent='Browser storage is unavailable. Export your choices now to keep them.';renderReport();}};
target.querySelector('#a-save').onclick=()=>write();target.querySelector('#a-clear')?.addEventListener('click',()=>write(true));target.querySelector('#a-inherit')?.addEventListener('click',()=>write(false,true));}
function renderReport(){const target=root.querySelector('#a-report');if(!target)return;const matches=loaded.filter(m=>selectedMatch==='all'||m.id===selectedMatch);if(!matches.length){report=null;const current=entries().find(m=>m.id===selectedMatch);target.innerHTML=`<div class="a-empty"><h3>${current?.status==='review'?'This sheet needs a closer look':entries().length?'Waiting for a readable scoresheet':'The first whistle is still ahead'}</h3><p>${esc(current?.reason||'Finished matches appear here after their scorecard and roster PDFs are published and checked.')}</p>${current?.source?.scorecardUrl?`<a href="${esc(safeUrl(current.source.scorecardUrl))}" target="_blank" rel="noopener">Open the scoresheet PDF ↗</a>`:''}</div>`;return;}
try{report=analyseTeam(matches,team,merged(),selectedSet||null);}catch(error){target.innerHTML=`<div class="a-notice error">${esc(error.message)} This match is excluded until the data is corrected.</div>`;return;}
const r=report,firstWins=r.serving.reduce((n,p)=>n+p.firstRalliesWon,0),turns=r.serving.reduce((n,p)=>n+p.servingTurns,0);const shown=r.serving.filter(p=>p.servingTurns>=minTurns).sort((a,b)=>(b[sort]??-Infinity)-(a[sort]??-Infinity)||b.servingTurns-a.servingTurns);
const stuck=r.rotation.filter(x=>x.rotation!=='Unconfirmed'&&x.received>=10).sort((a,b)=>a.sideOutPct-b.sideOutPct)[0];
target.innerHTML=`<div class="a-metrics"><div class="a-metric"><span>First serve, point won</span><strong>${pct(percentage(firstWins,turns))}</strong><small>${firstWins} of ${turns} serving turns</small></div><div class="a-metric"><span>Side-out rate</span><strong>${pct(percentage(r.total.sideOuts,r.total.received))}</strong><small>${r.total.sideOuts} of ${r.total.received} receptions</small></div><div class="a-metric"><span>In the sample</span><strong>${r.setCount} sets</strong><small>${r.matchCount} ${r.matchCount===1?'match':'matches'} · ${r.total.rallies} rallies</small></div><div class="a-metric"><span>Rotations confirmed</span><strong>${pct(r.confirmedPct)}</strong><small>${r.rotation.at(-1).rallies} rallies Unconfirmed</small></div></div>
${r.confirmedPct<100?'<div class="a-notice">Some rotations are <strong>Unconfirmed</strong>. Choose setters in “Who was setting?” above. Serving statistics are already available.</div>':''}
<section class="a-card"><div class="a-card-head"><div><h3>Make that first serve count.</h3><p>Runs and first-rally wins, player by player.</p></div><button id="a-serving-csv" class="a-small">Download serving CSV ↓</button></div><div class="a-toolbar"><label>Minimum turns <input id="a-min-turns" type="number" min="0" max="1000" value="${minTurns}"></label><label>Sort by <select id="a-sort">${[['servingTurns','Serving turns'],['firstRallyWinPct','First-rally win %'],['threePlusRunPct','3+ run %'],['pointsPerTurn','Points / turn'],['servesPerSet','Serves / set']].map(([v,t])=>`<option value="${v}" ${sort===v?'selected':''}>${t}</option>`).join('')}</select></label></div>${shown.length?table(shown,serveColumns,'Player serving analysis'):'<p class="a-note">No players meet this minimum. Lower the filter to see everyone.</p>'}<p class="a-note">Compare first-rally win % and points / turn alongside the number of turns. Fewer than 10 turns is a small sample. A point won while serving is a team rally win; this does not measure aces or serve errors. Scroll right for serves, sets and rates.</p></section>
<section class="a-card"><div class="a-card-head"><div><h3>Where do we get stuck?</h3><p>S1–S6 = setter position before the rally. Side-outs count in the receiving rotation, before the team rotates.</p></div><button id="a-rotation-csv" class="a-small">Download rotation CSV ↓</button></div><div class="a-bars">${r.rotation.slice(0,6).map(b=>`<div class="a-bar"><b>${b.rotation}</b><strong>${pct(b.sideOutPct)}</strong><small>${b.sideOuts}/${b.received} side-outs</small><div class="a-bar-track"><i style="width:${b.sideOutPct||0}%"></i></div></div>`).join('')}</div>${stuck?`<div class="a-notice"><strong>${stuck.rotation}</strong> has the lowest observed side-out rate: <strong>${pct(stuck.sideOutPct)}</strong> (${stuck.sideOuts}/${stuck.received}). Its longest receiving spell lost ${stuck.longestReceivingRun} consecutive points. Compare rotations with similar sample sizes.</div>`:'<p class="a-note">The comparison appears once a confirmed rotation has at least 10 received rallies.</p>'}${table(r.rotation,rotationColumns,'Rotation analysis')}<p class="a-note">Net points / 100 = 100 × (won − lost) / rallies. A dash means no observations. ${r.serving.reduce((n,p)=>n+p.setEndingTurns,0)} serving turns ended with a set-winning point; their runs stop at the set boundary.</p></section>`;
target.querySelector('#a-min-turns').onchange=e=>{minTurns=Math.max(0,Math.min(1000,+e.target.value||0));renderReport();};target.querySelector('#a-sort').onchange=e=>{sort=e.target.value;renderReport();};target.querySelector('#a-serving-csv').onclick=()=>download(`${team}-serving-${selectedMatch}.csv`,csv(shown,serveColumns),'text/csv;charset=utf-8');target.querySelector('#a-rotation-csv').onclick=()=>download(`${team}-rotations-${selectedMatch}.csv`,csv(r.rotation,[...rotationColumns,['longestReceivingRun','Longest receiving loss run'],['receivingStalls','Receiving spells losing 3+']]),'text/csv;charset=utf-8');}
function render(){if(!context)return;const list=entries(),ready=list.filter(m=>m.status==='ready'),teams=context.teams.map(t=>t.name),completed=context.fixtures.filter(f=>f.score&&f.completed!==false&&[f.home,f.away].includes(team)).length;
root.innerHTML=`<div class="a-hero"><div><p class="a-eyebrow">AFTER THE WHISTLE</p><h2>Find your team’s rhythm.</h2><p class="a-sub">The serves that build runs. The rotations that need a little work.</p></div>${team.startsWith('KSV')?'<img class="a-logo" src="./logos/KSV.png" alt="KSV">':''}</div>
<div class="a-filter"><label>Your team<select id="a-team">${teams.map(t=>`<option ${t===team?'selected':''}>${esc(t)}</option>`).join('')}</select></label><label>Match<select id="a-match"><option value="all">All available matches</option>${list.map(m=>`<option value="${esc(m.id)}" ${m.id===selectedMatch?'selected':''}>${esc(matchLabel(m))}${m.status==='ready'?'':' · '+m.status}</option>`).join('')}</select></label><label>Set<select id="a-set"><option value="">All sets</option>${(selectedMatch==='all'?[]:loaded.find(m=>m.id===selectedMatch)?.sets||[]).map(s=>`<option value="${s.number}" ${String(s.number)===selectedSet?'selected':''}>Set ${s.number}</option>`).join('')}</select></label></div>
<p class="a-status"><strong>${ready.length} of ${completed} finished matches available</strong> · ${list.filter(m=>m.status==='review').length} need review · Last analysis refresh: ${index?.lastCheckedAt?esc(new Date(index.lastCheckedAt).toLocaleString()):'not yet checked'}</p>
${loadError?`<div class="a-notice error" role="alert">${esc(loadError)} <button id="a-retry" class="a-small">Retry</button></div>`:''}
<details class="a-card a-setup" ${loaded.length&&selectedMatch!=='all'?'open':''}><summary>Who was setting? <small>Choose once for each match</small></summary><div id="a-setup-content"></div></details><div id="a-report"></div>
<details class="a-card a-help"><summary>How to read this</summary><dl><dt>Serving turn</dt><dd>A player’s consecutive serves, ending when their team loses the rally, the server changes or the set ends. A receiving point is not counted as a serve.</dd><dt>First-rally win %</dt><dd>The share of serving turns in which your team won the first served rally. This and points / turn make unequal playing time easier to compare.</dd><dt>Point-run bins</dt><dd>Team points won while that player serves. Every turn enters exactly one bin: 0, 1, 2, 3–4 or 5+. Set-ending runs are limited by the end of the set.</dd><dt>Unconfirmed</dt><dd>No selected setter is in the six rotation slots, the lineup is missing, or more than one setter fits your setting system. No setter position is guessed.</dd><dt>Sets played</dt><dd>Sets in which the player appears in a starting lineup or plays a rally after a substitution. Libero appearances and substitutions after the final rally cannot be counted here.</dd><dt>What the PDF cannot tell us</dt><dd>Aces, serve errors, serve speed, pass quality and attack efficiency. Libero exchanges are absent. Scans and unsupported layouts require review; they are not included as zero-stat matches.</dd></dl></details>
<details class="a-card"><summary>Scoresheets & data coverage</summary><div class="a-source-list">${list.map(m=>`<div class="a-source-row"><div><strong>${esc(m.home)} vs ${esc(m.away)}</strong><p>${esc(m.date)} · ${esc(m.status)}${m.reason?' · '+esc(m.reason):''}${m.refreshWarning?' · '+esc(m.refreshWarning):''}</p></div><div class="a-actions"><a href="${esc(safeUrl(m.matchUrl))}" target="_blank" rel="noopener">Result ↗</a>${m.source?.scorecardUrl?`<a href="${esc(safeUrl(m.source.scorecardUrl))}" target="_blank" rel="noopener">PDF ↗</a>`:''}</div></div>`).join('')||'<p class="a-note">No completed match PDFs have been collected for this team yet.</p>'}</div></details>
<div class="a-card"><div class="a-card-head"><div><h3>Keep everyone on the same page.</h3><p>Export your setter choices, or import the file a teammate shared.</p></div></div><div class="a-actions"><button id="a-export">Export setter choices ↓</button><button id="a-import">Import setter choices ↑</button><input id="a-import-file" type="file" accept=".json,application/json" hidden><span id="a-import-message" class="a-save-message" role="status"></span></div><p class="a-note">To publish these choices for everyone, replace <code>data/analysis-config.json</code> in your repository with the exported file. Personal choices in this browser take precedence.</p></div>`;
root.querySelector('#a-team').onchange=e=>{team=e.target.value;selectedMatch='all';selectedSet='';setupSet='';loadTeam();};root.querySelector('#a-match').onchange=e=>{selectedMatch=e.target.value;selectedSet='';setupMatch=selectedMatch==='all'?setupMatch:selectedMatch;setupSet='';render();};root.querySelector('#a-set').onchange=e=>{selectedSet=e.target.value;renderReport();};root.querySelector('#a-retry')?.addEventListener('click',()=>{index=null;loadTeam();});
root.querySelector('#a-export').onclick=()=>download('analysis-config.json',JSON.stringify(merged(),null,2)+'\n');root.querySelector('#a-import').onclick=()=>root.querySelector('#a-import-file').click();root.querySelector('#a-import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;const message=root.querySelector('#a-import-message');try{if(file.size>1000000)throw new Error('Configuration file is too large.');const incoming=validateConfig(JSON.parse(await file.text()));for(const [key,t]of Object.entries(incoming.teams)){local.teams[key]??={matches:{}};Object.assign(local.teams[key].matches,t.matches);}saveLocal();renderSetup();renderReport();message.textContent='Imported. Tables updated.';}catch(error){message.textContent='Import failed: '+error.message;}};
renderSetup();renderReport();}
async function loadTeam(){const token=++request;root.innerHTML='<div class="a-empty" role="status">Reading match analysis…</div>';try{if(!index){const values=await Promise.all([json('./data/analysis/index.json'),json('./data/analysis-config.json')]);if(token!==request)return;index=values[0];published=validateConfig(values[1]);}const list=entries().filter(m=>m.status==='ready');const results=await Promise.allSettled(list.map(m=>{if(!/^matches\/\d+\.json$/.test(m.file))throw new Error('Invalid match data path.');return json(`./data/analysis/${m.file}`);}));if(token!==request)return;loaded=results.filter(r=>r.status==='fulfilled').map(r=>r.value);loadError=results.some(r=>r.status==='rejected')?'Some match files could not be loaded. The available matches are shown.':'';if(selectedMatch!=='all'&&!entries().some(m=>m.id===selectedMatch))selectedMatch='all';render();}catch(error){if(token!==request)return;loadError=error.message;loaded=[];render();}}
function setContext(c){const changed=!context||+c.leagueId!==+context.leagueId;context=c;if(changed||!c.teams.some(t=>t.name===team)){team=(firstContext&&params.get('team'))||c.team||c.teams.find(t=>t.name.startsWith('KSV'))?.name||c.teams[0]?.name||'';if(!c.teams.some(t=>t.name===team))team=c.teams[0]?.name||'';selectedMatch=firstContext?(params.get('match')||'all'):'all';selectedSet='';setupSet='';}else if(c.team&&c.team!==team){team=c.team;selectedMatch='all';selectedSet='';}firstContext=false;loadTeam();}
window.addEventListener('volleyball-context',e=>setContext(e.detail));if(window.volleyballContext)setContext(window.volleyballContext);
const showView=view=>{const analysis=view==='analysis';document.getElementById('results-view').hidden=analysis;root.hidden=!analysis;document.body.classList.toggle('analysis-active',analysis);for(const btn of document.querySelectorAll('[data-view]'))btn.setAttribute('aria-pressed',String(btn.dataset.view===view));history.replaceState(null,'',`${location.pathname}${location.search}${analysis?'#analysis':''}`);};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));showView(location.hash==='#analysis'?'analysis':'results');
