import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {analyseTeam,rotationLabel,validateConfig,validateMatch} from '../analysis-engine.js';
const real=JSON.parse(fs.readFileSync(new URL('fixtures/76141-match.json',import.meta.url)));
const configuration=selection=>({version:1,teams:{'4125:KSV.3':{matches:{'76141':selection}}}});
test('the manually counted first KSV set has 23 serves and 13 serving turns',()=>{
  const r=analyseTeam([real],'KSV.3',{},1);assert.equal(r.total.serves,23);assert.equal(r.total.serveWins,10);assert.equal(r.total.sideOuts,12);assert.equal(r.serving.reduce((n,p)=>n+p.servingTurns,0),13);
  const expected={'10':[3,0,3,0],'11':[2,2,6,3],'4':[2,1,3,1],'1':[2,0,2,0],'14':[2,2,6,2],'8':[2,1,3,1]};
  for(const p of r.serving)assert.deepEqual([p.servingTurns,p.firstRalliesWon,p.serves,p.bestPointRun],expected[p.numbers[0]]);
});
test('all real rallies are counted when no setter is specified',()=>{const r=analyseTeam([real],'KSV.3');assert.equal(r.rotation.at(-1).rallies,175);assert.equal(r.total.serves,96);assert.equal(r.total.serveWins,48);assert.equal(r.total.received,79);assert.equal(r.total.sideOuts,49);assert.equal(r.confirmedPct,0);assert.equal(r.rotation[0].sideOutPct,null);});
test('setter position is read before a side-out, then moves on rotation',()=>{const r=analyseTeam([real],'KSV.3',configuration({setters:['10']}),1);assert.equal(r.rotation.find(x=>x.rotation==='S1').serves,3);assert.equal(r.rotation.find(x=>x.rotation==='S1').sideOuts,2);assert.equal(r.rotation.find(x=>x.rotation==='S6').serves,6);assert.equal(r.confirmedPct,100);});
test('missing and ambiguous setters never get guessed; backups and systems are explicit',()=>{const l=['5','1','2','8','4','6'];assert.equal(rotationLabel(l,[]),'Unconfirmed');assert.equal(rotationLabel(l,['5','8']),'Unconfirmed');assert.equal(rotationLabel(l,{setters:['5','8'],system:'back-row'}),'S1');assert.equal(rotationLabel(l,{setters:['5','8'],system:'front-row'}),'S4');assert.equal(rotationLabel(l,{setters:['7'],fallbacks:['8']}),'S4');assert.equal(rotationLabel(l,{setters:['5'],fallbacks:['8']}),'S1');assert.equal(rotationLabel(null,['5']),'Unconfirmed');});
test('substitutions change which selected setter is in the rotation',()=>{const r=analyseTeam([real],'KSV.3',configuration({setters:['7'],fallbacks:['14']}),3);assert.equal(r.confirmedPct,100);assert.equal(r.total.rallies,41);assert.ok(real.sets[2].rallies.some(x=>x.lineups.away.includes('7')));assert.ok(real.sets[2].rallies.some(x=>x.lineups.away.includes('14')));});
test('rates are pooled, IDs deduplicate matches, and point bins account for every turn',()=>{const one=analyseTeam([real],'KSV.3');const dup=analyseTeam([real,real],'KSV.3');assert.deepEqual(one,dup);for(const p of one.serving){assert.equal(p.servingTurns,p.zeroPointTurns+p.onePointTurns+p.twoPointTurns+p.threeToFourPointTurns+p.fivePlusPointTurns);assert.equal(p.firstRalliesWon,p.servingTurns-p.zeroPointTurns);assert.equal(p.serves,p.serveWins+p.servingTurns-p.setEndingTurns);}assert.equal(one.total.rallies,one.total.serves+one.total.received);});
test('home and away perspectives complement each other',()=>{const a=analyseTeam([real],real.home),b=analyseTeam([real],real.away);assert.equal(a.total.serves,b.total.received);assert.equal(a.total.serveWins+b.total.sideOuts,a.total.serves);assert.equal(b.total.serveWins+a.total.sideOuts,b.total.serves);});
test('unknown lineups retain rallies under Unconfirmed',()=>{const copy=structuredClone(real);for(const s of copy.sets)for(const r of s.rallies)delete r.lineups;const a=analyseTeam([copy],'KSV.3',configuration({setters:['10']}));assert.equal(a.total.rallies,175);assert.equal(a.rotation.at(-1).rallies,175);assert.equal(a.total.serves,96);});
test('a set override applies only to that set and an empty override clears confirmation',()=>{const r=analyseTeam([real],'KSV.3',configuration({setters:['10'],sets:{'1':{setters:[]}}}));assert.equal(r.rotation.at(-1).rallies,47);});
test('bad data and malformed imported configurations are rejected',()=>{const bad=structuredClone(real);bad.sets[0].rallies.pop();assert.throws(()=>validateMatch(bad),/totals/);assert.throws(()=>validateConfig({version:1,teams:{'4125:KSV.3':{matches:{'76141':{setters:['<script>']}}}}}),/shirt/);assert.throws(()=>validateConfig({version:2,teams:{}}));assert.deepEqual(validateConfig({version:1,teams:{}}),{version:1,teams:{}});});
